@baseUrl = http://localhost:3000/api

@resourceName = cities

## Categories

# @name getAllCities

GET {{baseUrl}}/{{resourceName}}

###

###

# @name addNewCities
POST {{baseUrl}}/{{resourceName}}
Content-Type: application/json

{
    "name": "Laptop"
}

###

# @name updateCities
PATCH {{baseUrl}}/{{resourceName}}/2
Content-Type: application/json

{
    "name": "Laptop New"
}

###

# @name removeCities
DELETE  {{baseUrl}}/{{resourceName}}/2
Content-Type: application/json
