@baseUrl = http://localhost:3000/api

@resourceName = students

## Categories

# @name getAllStudents

GET {{baseUrl}}/{{resourceName}}

###

###

# @name addNewStudents
POST {{baseUrl}}/{{resourceName}}
Content-Type: application/json

{
    "name": "Laptop"
}

###

# @name updateStudents
PATCH {{baseUrl}}/{{resourceName}}/2
Content-Type: application/json

{
    "name": "Laptop New"
}

###

# @name removeStudents
DELETE  {{baseUrl}}/{{resourceName}}/2
Content-Type: application/json
